// target-vite-vue/src/App.vue
<script setup lang="ts">
import HelloBlazor from './components/HelloBlazor.vue'
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <a href="https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor" target="_blank">
      <img src="./assets/blazor.svg" className="logo blazor" alt="Blazor logo" />
    </a>
  </div>
  <HelloBlazor msg="Vite + Vue + Blazor" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// target-vite-react/src/App.tsx

import reactLogo from './assets/react.svg'
import viteLogo from './assets/vite.svg'
import blazorLogo from './assets/blazor.svg'
import BlazorComponent from './blazor/blazor-component'
import './App.css'

function App() {
  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <a href="https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor" target="_blank">
          <img src={blazorLogo} className="logo blazor" alt="Blazor logo" />
        </a>
      </div>
      <h1>Vite + React + Blazor</h1>
      <BlazorComponent />
      <p className="read-the-docs">
        Click on the Vite, React or Blazor logo to learn more
      </p>
    </>
  )
}

export default App
