// target-gatsby/src/blazor/blazor-component.tsx
import "./blazor-component.css";
import { BlazorComponentSetup } from "./blazor-component-setup";
import React, { useEffect, useRef, useState } from "react";

export default function BlazorComponent() {
    const [count, setCount] = useState(0);
    const [isInitialized, setIsInitialized] = useState(false);
    const blazorComponentSetupRef = useRef(new BlazorComponentSetup());

    const initialize = async () => {
        const blazorComponentSetup = blazorComponentSetupRef.current;
        setIsInitialized(await blazorComponentSetup.initializeAsync());
    };

    const sendMessage = () => {
        const blazorComponentSetup = blazorComponentSetupRef.current;
        blazorComponentSetup.sendMessage();
    }

    const incrementCount = () => {
        setCount(count => count + 1);
    }

    useEffect(() => {
        initialize();
        return () => {
            setIsInitialized(false);
        }
    }, []);
    return (
        <div className="flex-column-center">{
            isInitialized &&
            <div className='card-blazor'>
                {React.createElement('blazor-custom-element-scoped', { 'element-title': 'Blazor Micro Frontend (Scoped)' })}
                {React.createElement('blazor-custom-element', { 'element-title': 'Blazor Micro Frontend (Unscoped)' })}
            </div>}
            <div id="blazor-message">No message from Blazor received.</div>
            <div className="card">
                <div>
                    <button onClick={sendMessage}>
                        Send message to Blazor
                    </button>
                    <button onClick={incrementCount}>
                        Count is {count}
                    </button>
                </div>
            </div>
        </div>
    );
}

// target-angular/src/app/blazor/blazor-component.component.ts
import { BlazorComponentSetup } from './blazor-component-setup';
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-blazor-component',
  imports: [],
  templateUrl: './blazor-component.component.html',
  styleUrl: './blazor-component.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class BlazorComponentComponent implements OnInit, OnDestroy {
  private readonly blazorComponentSetup: BlazorComponentSetup = new BlazorComponentSetup();

  public isInitialized: boolean = false;
  public count: number = 0;

  public ngOnInit(): void {
    (async () => {
      this.isInitialized = await this.blazorComponentSetup.initializeAsync();
    })();
  }

  public sendMessage(): void {
    this.blazorComponentSetup.sendMessage();
  }

  public incrementCount(): void {
    this.count += 1;
  }

  public ngOnDestroy(): void {
    this.isInitialized = false;
  }
}

<div class="flex-column-center">
  @if (isInitialized) {
    <div class='card-blazor'>
      <blazor-custom-element-scoped element-title='Blazor Micro Frontend (Scoped)'></blazor-custom-element-scoped>
      <blazor-custom-element element-title='Blazor Micro Frontend (Unscoped)'></blazor-custom-element>
    </div>
  }
  <div id="blazor-message">No message from Blazor received.</div>
  <div class="card">
    <div>
      <button (click)="sendMessage()">
        Send message to Blazor
      </button>
      <button (click)="incrementCount()">
        Count is {{count}}
      </button>
    </div>
  </div>
</div>
