// target-remix/app/blazor/blazor-component.tsx
import "./blazor-component.css";
import { BlazorComponentSetup } from "./blazor-component-setup";
import React, { useEffect, useRef, useState } from "react";

export default function BlazorComponent() {
    const [count, setCount] = useState(0);
    const [isInitialized, setIsInitialized] = useState(false);
    const blazorComponentSetupRef = useRef(new BlazorComponentSetup());

    const initialize = async () => {
        const blazorComponentSetup = blazorComponentSetupRef.current;
        setIsInitialized(await blazorComponentSetup.initializeAsync());
    };

    const sendMessage = () => {
        const blazorComponentSetup = blazorComponentSetupRef.current;
        blazorComponentSetup.sendMessage();
    }

    const incrementCount = () => {
        setCount(count => count + 1);
    }

    useEffect(() => {
        initialize();
        return () => {
            setIsInitialized(false);
        }
    }, []);
    return (
        <div className="flex-column-center">{
            isInitialized &&
            <div className='card-blazor'>
                {React.createElement('blazor-custom-element-scoped', { 'element-title': 'Blazor Micro Frontend (Scoped)' })}
                {React.createElement('blazor-custom-element', { 'element-title': 'Blazor Micro Frontend (Unscoped)' })}
            </div>}
            <div id="blazor-message">No message from blazor received.</div>
            <div className="card">
                <div>
                    <button onClick={sendMessage}>
                        Send message to blazor
                    </button>
                    <button onClick={incrementCount}>
                        Count is {count}
                    </button>
                </div>
            </div>
        </div>
    );
}

// target-vite-vue/src/blazor/BlazorComponent.vue
<script lang="ts">
import "./blazor-component.css";
import { BlazorComponentSetup } from "./blazor-component-setup";
import { defineComponent, onMounted, onUnmounted, ref } from 'vue';
  
export default defineComponent({
    name: 'BlazorComponent',
    setup() {
      const count = ref(0);
      const isInitialized = ref(false);
      const blazorComponentSetupRef = ref(new BlazorComponentSetup());
      
      const initialize = async () => {
        const blazorComponentSetup = blazorComponentSetupRef.value;
        isInitialized.value = await blazorComponentSetup.initializeAsync();
      };

      const sendMessage = () => {
        const blazorComponentSetup = blazorComponentSetupRef.value;
        blazorComponentSetup.sendMessage();
      }
      
      const incrementCount = () => {
        count.value += 1;
      };

      onMounted(() => {    
        initialize();
      });
      
      onUnmounted(() => {
        isInitialized.value = false;
      });
  
      return {
        count,
        isInitialized,
        sendMessage,
        incrementCount,
      };
    },
});
</script>
<template>
    <div class="flex-column-center">
      <div class="card-blazor" v-if="isInitialized">
        <blazor-custom-element-scoped element-title="Blazor Micro Frontend (Scoped)"></blazor-custom-element-scoped>
        <blazor-custom-element element-title="Blazor Micro Frontend (Unscoped)"></blazor-custom-element>
      </div>
      <div id="blazor-message">No message from blazor received.</div>
      <div class="card">
        <div>
          <button @click="sendMessage">Send message to blazor</button>
          <button @click="incrementCount">Count is {{ count }}</button>
        </div>
      </div>
    </div>
</template>
